spring.application.name=capital-service
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/safraplus_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:safraplus}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:safraplus}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

api.security.token.secret=safraplus-nosso-segredo-super-secreto-para-proteger-o-jwt