spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/safraplus_db
spring.datasource.username=safraplus
spring.datasource.password=safraplus
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG

api.security.token.secret=safraplus-nosso-segredo-super-secreto-para-proteger-o-jwt